In [1]:
import matplotlib.pyplot as plt
import matplotlib.animation
import seaborn as sns
import numpy as np
import json

In [6]:
landscape_ground = tuple([4]*2)
#we add the one to avoid 0 fitness
landscape = np.fromfunction(lambda a, b: a+b+1, landscape_ground)




In [7]:
print(landscape)

[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]
