In [2]:
import numpy as np
x = np.random.choice([-1,0, 1], size=(5,5), p=[0.05,0.9,0.05])

In [10]:
print(x)

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0 -1  0  0  0]]


In [11]:
x[:,[0,1,1,0]]

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0, -1, -1,  0]])

In [11]:
x = [1,2,3,4,5,8,9,10,11,12, 6,7,3, 10,11,12, 61,5,11,12, 6,10,11,12, 6,3,32,12,6,12,21,5,12]

pop_size = len(x)
print(pop_size)
num_10_perc = int(len(x)*0.1)
print(num_10_perc)
top_positions = np.argsort(x)
print(top_positions[-3:])
print(top_positions)
num_asex = len(np.where(top_positions < int(pop_size/2)))
percent_top_asex = num_asex/num_10_perc
percent_top_asex

33
3
[30 26 16]
[ 0  1 25 12  2  3  4 17 31 20 28 24 10 11  5  6 13  7 21  8 18 22 14 29
 27 32 19 15  9 23 30 26 16]


0.3333333333333333

In [19]:
list(pairs)

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10), (11, 12)]