In [9]:
import numpy as np
x = np.random.choice([-1,0, 1], size=(5,5), p=[0.05,0.9,0.05])

In [10]:
print(x)

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0 -1  0  0  0]]


In [11]:
x[:,[0,1,1,0]]

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0, -1, -1,  0]])

In [18]:
x = [1,2,3,4,5,6,7,8,9,10,11,12]
pairs = zip(x[::2], x[1::2])

In [19]:
list(pairs)

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10), (11, 12)]